### ISSUE TITLE
Training and Test Scripts

### ISSUE THREAD

**Issue by TouqeerAhmad** [oshadajay/CeyMo#2]
Hi, I was looking for training and test scripts, but could not find them. Can you please direct where they are located or share them 

Thanks!

**Comment by oshadajay** [comment]
Hi, 

Unfortunately, our project was carried out with an external company and we will be only sharing the dataset and the evaluation script. We used the Tensorflow Object Detection API (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/) for training the models. 

Thank you!
