### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by blindwang** [oshadajay/CeyMo#3]
Hi, I am wondering whether the pretrained model will be available? Thank you very much for your contribution.

**Comment by oshadajay** [comment]
Hi,

Unfortunately, our project was carried out with an external company and we will be only sharing the dataset and the evaluation script. We used the Tensorflow Object Detection API (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/) for training the models.

Thank you!
