### ISSUE TITLE
Parameters of inverse perspective transform

### ISSUE THREAD

**Issue by stupidZ** [oshadajay/CeyMo#6]
Hi, I would like to do the inverse perspective transform(IPT). Could you pls provide the parameters for IPT? Thank you for your contribution.

**Comment by oshadajay** [comment]
Hi, we calculated the parameters for the inverse perspective transform by observation. As in selecting four coordinates from the original image which should match with the corners of the resultant image. Therefore IPT parameters are not based on camera intrinsic parameters.
