### ISSUE TITLE
Models

### ISSUE THREAD

**Issue by Peregalli** [oshadajay/CeyMo#9]
Hello! Congratulations on your work! I wanted to ask if you could make the trained models mentioned in the paper available. Thank you very much!

**Comment by oshadajay** [comment]
Hi,

Thank you for showing interest in our work. Unfortunately, our project was carried out with an external company and we will be only sharing the dataset and the evaluation script. We used the Tensorflow Object Detection API (https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/) for training the models.

Thank you!

**Comment by Peregalli** [comment]
Well, congrats for turning in that direction and thank for your response.

**Comment by Peregalli** [comment]
Well, congrats for turning in that direction and thank for your response.
